/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as JapanExRouteImport } from './routes/japan-ex'
import { Route as FoodieExRouteImport } from './routes/foodie-ex'
import { Route as ChinaExRouteImport } from './routes/china-ex'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const JapanExRoute = JapanExRouteImport.update({
  id: '/japan-ex',
  path: '/japan-ex',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodieExRoute = FoodieExRouteImport.update({
  id: '/foodie-ex',
  path: '/foodie-ex',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinaExRoute = ChinaExRouteImport.update({
  id: '/china-ex',
  path: '/china-ex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/china-ex': typeof ChinaExRoute
  '/foodie-ex': typeof FoodieExRoute
  '/japan-ex': typeof JapanExRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/china-ex': typeof ChinaExRoute
  '/foodie-ex': typeof FoodieExRoute
  '/japan-ex': typeof JapanExRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/china-ex': typeof ChinaExRoute
  '/foodie-ex': typeof FoodieExRoute
  '/japan-ex': typeof JapanExRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/china-ex'
    | '/foodie-ex'
    | '/japan-ex'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/china-ex'
    | '/foodie-ex'
    | '/japan-ex'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/china-ex'
    | '/foodie-ex'
    | '/japan-ex'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinaExRoute: typeof ChinaExRoute
  FoodieExRoute: typeof FoodieExRoute
  JapanExRoute: typeof JapanExRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japan-ex': {
      id: '/japan-ex'
      path: '/japan-ex'
      fullPath: '/japan-ex'
      preLoaderRoute: typeof JapanExRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foodie-ex': {
      id: '/foodie-ex'
      path: '/foodie-ex'
      fullPath: '/foodie-ex'
      preLoaderRoute: typeof FoodieExRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/china-ex': {
      id: '/china-ex'
      path: '/china-ex'
      fullPath: '/china-ex'
      preLoaderRoute: typeof ChinaExRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinaExRoute: ChinaExRoute,
  FoodieExRoute: FoodieExRoute,
  JapanExRoute: JapanExRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
